apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-api.fullname" . }}
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.python.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "python-api.selectorLabels" . | nindent 6 }}
      app: python
  template:
    metadata:
      labels:
        app: python
        {{- include "python-api.labels" . | nindent 8 }}
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - python
      #       topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: python
      enableServiceLinks: false
      containers:
      - name: python-api
        image: {{ with .Values.registry }}{{ . }}/{{ end }}{{ .Values.python.image.name }}:{{ .Values.python.image.tag}}
        ports:
          - containerPort: 5002
            name: api
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
        readinessProbe:
          tcpSocket:
            port: api
        envFrom:
          - configMapRef:
              name: {{ include "python-api.fullname" . }}
        resources:
          {{- toYaml .Values.python.resources | nindent 10 }}