apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-1
  labels:
    name: myapp1
spec:
  enableServiceLinks: false
  containers:
  - name: python-api
    image: krajewskim/python-api:new
    resources: {}
    ports:
      - containerPort: 5002
        name: api
    livenessProbe:
      httpGet:
        path: /healthz
        port: api
    readinessProbe:
      tcpSocket:
        port: api