# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc
#   labels:
#     projekt: python
# spec:
#   resources:
#     requests:
#       storage: 10Mi
#   accessModes:
#     - ReadWriteOnce
