apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- namespace.yaml
- ../../bases

namespace: python
patches:
- path: patch_python_deployment.yaml
- path: patch_ingress.yaml
